// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VIP_GATERING.Infrastructure.Data;

#nullable disable

namespace VIP_GATERING.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251014015803_MenuScopeSucursalEmpresa")]
    partial class MenuScopeSucursalEmpresa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rnc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaTermino")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Opcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Opciones");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.OpcionMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OpcionIdA")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OpcionIdB")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OpcionIdC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("OpcionIdA");

                    b.HasIndex("OpcionIdB");

                    b.HasIndex("OpcionIdC");

                    b.ToTable("OpcionesMenu");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.RespuestaFormulario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OpcionMenuId")
                        .HasColumnType("TEXT");

                    b.Property<char>("Seleccion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("OpcionMenuId");

                    b.ToTable("RespuestasFormulario");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.RolUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RolId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RolesUsuario");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("Empleados")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Menu", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VIP_GATERING.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.OpcionMenu", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Menu", "Menu")
                        .WithMany("OpcionesPorDia")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.Opcion", "OpcionA")
                        .WithMany()
                        .HasForeignKey("OpcionIdA")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VIP_GATERING.Domain.Entities.Opcion", "OpcionB")
                        .WithMany()
                        .HasForeignKey("OpcionIdB")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VIP_GATERING.Domain.Entities.Opcion", "OpcionC")
                        .WithMany()
                        .HasForeignKey("OpcionIdC")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Menu");

                    b.Navigation("OpcionA");

                    b.Navigation("OpcionB");

                    b.Navigation("OpcionC");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.RespuestaFormulario", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.OpcionMenu", "OpcionMenu")
                        .WithMany("Respuestas")
                        .HasForeignKey("OpcionMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("OpcionMenu");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.RolUsuario", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Rol", "Rol")
                        .WithMany("RolesUsuario")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RolesUsuario")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Sucursal", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Sucursales")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Empleado", "Empleado")
                        .WithOne("Usuario")
                        .HasForeignKey("VIP_GATERING.Domain.Entities.Usuario", "EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Menu", b =>
                {
                    b.Navigation("OpcionesPorDia");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.OpcionMenu", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Rol", b =>
                {
                    b.Navigation("RolesUsuario");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Sucursal", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RolesUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
