// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VIP_GATERING.Infrastructure.Data;

#nullable disable

namespace VIP_GATERING.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Borrado")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<bool>("EsJefe")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsSubsidiado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<int?>("SubsidioTipo")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SubsidioValor")
                        .HasColumnType("numeric");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.EmpleadoLocalizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("LocalizacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalizacionId");

                    b.HasIndex("EmpleadoId", "LocalizacionId")
                        .IsUnique();

                    b.ToTable("EmpleadosLocalizaciones");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.EmpleadoSucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("EmpleadoId", "SucursalId")
                        .IsUnique();

                    b.ToTable("EmpleadosSucursales");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactoNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactoTelefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rnc")
                        .HasColumnType("text");

                    b.Property<bool>("SubsidiaEmpleados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("SubsidioTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("SubsidioValor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(75m);

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Borrado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Localizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("IndicacionesEntrega")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SucursalId", "Nombre")
                        .IsUnique();

                    b.ToTable("Localizaciones");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<bool>("EncuestaCerradaManualmente")
                        .HasColumnType("boolean");

                    b.Property<bool>("EncuestaReabiertaManualmente")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaCierreManual")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaTermino")
                        .HasColumnType("date");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.MenuAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("OpcionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OpcionId");

                    b.HasIndex("MenuId", "OpcionId")
                        .IsUnique();

                    b.ToTable("MenusAdicionales");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.MenuConfiguracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreadoUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DiasAnticipoSemanaActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("HoraLimiteEdicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(432000000000L);

                    b.Property<bool>("PermitirEdicionSemanaActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesMenu");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Opcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Borrado")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EsSubsidiado")
                        .HasColumnType("boolean");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<bool>("LlevaItbis")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Opciones");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.OpcionHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HorarioId")
                        .HasColumnType("integer");

                    b.Property<int>("OpcionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HorarioId");

                    b.HasIndex("OpcionId", "HorarioId")
                        .IsUnique();

                    b.ToTable("OpcionesHorarios");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.OpcionMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<int?>("HorarioId")
                        .HasColumnType("integer");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int?>("OpcionIdA")
                        .HasColumnType("integer");

                    b.Property<int?>("OpcionIdB")
                        .HasColumnType("integer");

                    b.Property<int?>("OpcionIdC")
                        .HasColumnType("integer");

                    b.Property<int?>("OpcionIdD")
                        .HasColumnType("integer");

                    b.Property<int?>("OpcionIdE")
                        .HasColumnType("integer");

                    b.Property<int>("OpcionesMaximas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HorarioId");

                    b.HasIndex("MenuId");

                    b.HasIndex("OpcionIdA");

                    b.HasIndex("OpcionIdB");

                    b.HasIndex("OpcionIdC");

                    b.HasIndex("OpcionIdD");

                    b.HasIndex("OpcionIdE");

                    b.ToTable("OpcionesMenu");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.RespuestaFormulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdicionalOpcionId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("LocalizacionEntregaId")
                        .HasColumnType("integer");

                    b.Property<int>("OpcionMenuId")
                        .HasColumnType("integer");

                    b.Property<char>("Seleccion")
                        .HasColumnType("character(1)");

                    b.Property<int>("SucursalEntregaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdicionalOpcionId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("LocalizacionEntregaId");

                    b.HasIndex("OpcionMenuId");

                    b.HasIndex("SucursalEntregaId");

                    b.ToTable("RespuestasFormulario");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.RolUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RolesUsuario");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Borrado")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("SubsidiaEmpleados")
                        .HasColumnType("boolean");

                    b.Property<int?>("SubsidioTipo")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SubsidioValor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.SucursalHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HorarioId")
                        .HasColumnType("integer");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HorarioId");

                    b.HasIndex("SucursalId", "HorarioId")
                        .IsUnique();

                    b.ToTable("SucursalesHorarios");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VIP_GATERING.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("VIP_GATERING.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("VIP_GATERING.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("VIP_GATERING.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("VIP_GATERING.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("VIP_GATERING.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("VIP_GATERING.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("Empleados")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.EmpleadoLocalizacion", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Empleado", "Empleado")
                        .WithMany("LocalizacionesAsignadas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.Localizacion", "Localizacion")
                        .WithMany("EmpleadosAsignados")
                        .HasForeignKey("LocalizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Localizacion");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.EmpleadoSucursal", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Empleado", "Empleado")
                        .WithMany("SucursalesAsignadas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("EmpleadosAsignados")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Localizacion", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("Localizaciones")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Menu", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VIP_GATERING.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.MenuAdicional", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Menu", "Menu")
                        .WithMany("Adicionales")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.Opcion", "Opcion")
                        .WithMany()
                        .HasForeignKey("OpcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Opcion");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.OpcionHorario", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Horario", "Horario")
                        .WithMany("Opciones")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.Opcion", "Opcion")
                        .WithMany("Horarios")
                        .HasForeignKey("OpcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horario");

                    b.Navigation("Opcion");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.OpcionMenu", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Horario", "Horario")
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VIP_GATERING.Domain.Entities.Menu", "Menu")
                        .WithMany("OpcionesPorDia")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.Opcion", "OpcionA")
                        .WithMany()
                        .HasForeignKey("OpcionIdA")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VIP_GATERING.Domain.Entities.Opcion", "OpcionB")
                        .WithMany()
                        .HasForeignKey("OpcionIdB")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VIP_GATERING.Domain.Entities.Opcion", "OpcionC")
                        .WithMany()
                        .HasForeignKey("OpcionIdC")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VIP_GATERING.Domain.Entities.Opcion", "OpcionD")
                        .WithMany()
                        .HasForeignKey("OpcionIdD")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VIP_GATERING.Domain.Entities.Opcion", "OpcionE")
                        .WithMany()
                        .HasForeignKey("OpcionIdE")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Horario");

                    b.Navigation("Menu");

                    b.Navigation("OpcionA");

                    b.Navigation("OpcionB");

                    b.Navigation("OpcionC");

                    b.Navigation("OpcionD");

                    b.Navigation("OpcionE");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.RespuestaFormulario", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Opcion", "AdicionalOpcion")
                        .WithMany()
                        .HasForeignKey("AdicionalOpcionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VIP_GATERING.Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.Localizacion", "LocalizacionEntrega")
                        .WithMany()
                        .HasForeignKey("LocalizacionEntregaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VIP_GATERING.Domain.Entities.OpcionMenu", "OpcionMenu")
                        .WithMany("Respuestas")
                        .HasForeignKey("OpcionMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.Sucursal", "SucursalEntrega")
                        .WithMany()
                        .HasForeignKey("SucursalEntregaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdicionalOpcion");

                    b.Navigation("Empleado");

                    b.Navigation("LocalizacionEntrega");

                    b.Navigation("OpcionMenu");

                    b.Navigation("SucursalEntrega");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.RolUsuario", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Rol", "Rol")
                        .WithMany("RolesUsuario")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RolesUsuario")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Sucursal", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Sucursales")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.SucursalHorario", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Horario", "Horario")
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIP_GATERING.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horario");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("VIP_GATERING.Domain.Entities.Empleado", "Empleado")
                        .WithOne("Usuario")
                        .HasForeignKey("VIP_GATERING.Domain.Entities.Usuario", "EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("LocalizacionesAsignadas");

                    b.Navigation("SucursalesAsignadas");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Horario", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Localizacion", b =>
                {
                    b.Navigation("EmpleadosAsignados");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Adicionales");

                    b.Navigation("OpcionesPorDia");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Opcion", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.OpcionMenu", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Rol", b =>
                {
                    b.Navigation("RolesUsuario");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Sucursal", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("EmpleadosAsignados");

                    b.Navigation("Localizaciones");
                });

            modelBuilder.Entity("VIP_GATERING.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RolesUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
