CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpleadoId" integer,
    "EmpresaId" integer,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "ConfiguracionesMenu" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PermitirEdicionSemanaActual" boolean NOT NULL DEFAULT TRUE,
    "DiasAnticipoSemanaActual" integer NOT NULL DEFAULT 1,
    "HoraLimiteEdicion" bigint NOT NULL DEFAULT 432000000000,
    "CreadoUtc" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ActualizadoUtc" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_ConfiguracionesMenu" PRIMARY KEY ("Id")
);

CREATE TABLE "Empresas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Rnc" text,
    "ContactoNombre" text NOT NULL,
    "ContactoTelefono" text NOT NULL,
    "Direccion" text NOT NULL,
    "SubsidiaEmpleados" boolean NOT NULL DEFAULT TRUE,
    "SubsidioTipo" integer NOT NULL DEFAULT 0,
    "SubsidioValor" numeric NOT NULL DEFAULT 75.0,
    CONSTRAINT "PK_Empresas" PRIMARY KEY ("Id")
);

CREATE TABLE "Horarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Orden" integer NOT NULL,
    "Activo" boolean NOT NULL,
    "Borrado" boolean NOT NULL,
    CONSTRAINT "PK_Horarios" PRIMARY KEY ("Id")
);

CREATE TABLE "Opciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" text,
    "Nombre" text NOT NULL,
    "Descripcion" text,
    "Costo" numeric NOT NULL,
    "Precio" numeric,
    "EsSubsidiado" boolean NOT NULL,
    "LlevaItbis" boolean NOT NULL,
    "ImagenUrl" text,
    "Borrado" boolean NOT NULL,
    CONSTRAINT "PK_Opciones" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Sucursales" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Direccion" text,
    "Borrado" boolean NOT NULL,
    "SubsidiaEmpleados" boolean,
    "SubsidioTipo" integer,
    "SubsidioValor" numeric,
    "EmpresaId" integer NOT NULL,
    CONSTRAINT "PK_Sucursales" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sucursales_Empresas_EmpresaId" FOREIGN KEY ("EmpresaId") REFERENCES "Empresas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OpcionesHorarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OpcionId" integer NOT NULL,
    "HorarioId" integer NOT NULL,
    CONSTRAINT "PK_OpcionesHorarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OpcionesHorarios_Horarios_HorarioId" FOREIGN KEY ("HorarioId") REFERENCES "Horarios" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OpcionesHorarios_Opciones_OpcionId" FOREIGN KEY ("OpcionId") REFERENCES "Opciones" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Empleados" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" text,
    "Nombre" text,
    "Borrado" boolean NOT NULL,
    "SucursalId" integer NOT NULL,
    "EsSubsidiado" boolean NOT NULL DEFAULT TRUE,
    "SubsidioTipo" integer,
    "SubsidioValor" numeric,
    "Estado" integer NOT NULL,
    "EsJefe" boolean NOT NULL,
    CONSTRAINT "PK_Empleados" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Empleados_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Localizaciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "SucursalId" integer NOT NULL,
    "EmpresaId" integer NOT NULL,
    "Direccion" text NOT NULL,
    "IndicacionesEntrega" text NOT NULL,
    CONSTRAINT "PK_Localizaciones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Localizaciones_Empresas_EmpresaId" FOREIGN KEY ("EmpresaId") REFERENCES "Empresas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Localizaciones_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Menus" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FechaInicio" date NOT NULL,
    "FechaTermino" date NOT NULL,
    "EmpresaId" integer,
    "SucursalId" integer,
    "EncuestaCerradaManualmente" boolean NOT NULL,
    "FechaCierreManual" timestamp with time zone,
    "EncuestaReabiertaManualmente" boolean NOT NULL,
    CONSTRAINT "PK_Menus" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Menus_Empresas_EmpresaId" FOREIGN KEY ("EmpresaId") REFERENCES "Empresas" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Menus_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SucursalesHorarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SucursalId" integer NOT NULL,
    "HorarioId" integer NOT NULL,
    CONSTRAINT "PK_SucursalesHorarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SucursalesHorarios_Horarios_HorarioId" FOREIGN KEY ("HorarioId") REFERENCES "Horarios" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SucursalesHorarios_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EmpleadosSucursales" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpleadoId" integer NOT NULL,
    "SucursalId" integer NOT NULL,
    CONSTRAINT "PK_EmpleadosSucursales" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmpleadosSucursales_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EmpleadosSucursales_Sucursales_SucursalId" FOREIGN KEY ("SucursalId") REFERENCES "Sucursales" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "ContrasenaHash" text NOT NULL,
    "EmpleadoId" integer NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Usuarios_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EmpleadosLocalizaciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpleadoId" integer NOT NULL,
    "LocalizacionId" integer NOT NULL,
    CONSTRAINT "PK_EmpleadosLocalizaciones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmpleadosLocalizaciones_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EmpleadosLocalizaciones_Localizaciones_LocalizacionId" FOREIGN KEY ("LocalizacionId") REFERENCES "Localizaciones" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MenusAdicionales" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MenuId" integer NOT NULL,
    "OpcionId" integer NOT NULL,
    CONSTRAINT "PK_MenusAdicionales" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MenusAdicionales_Menus_MenuId" FOREIGN KEY ("MenuId") REFERENCES "Menus" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MenusAdicionales_Opciones_OpcionId" FOREIGN KEY ("OpcionId") REFERENCES "Opciones" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "OpcionesMenu" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OpcionIdA" integer,
    "OpcionIdB" integer,
    "OpcionIdC" integer,
    "OpcionIdD" integer,
    "OpcionIdE" integer,
    "OpcionesMaximas" integer NOT NULL,
    "MenuId" integer NOT NULL,
    "DiaSemana" integer NOT NULL,
    "HorarioId" integer,
    CONSTRAINT "PK_OpcionesMenu" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OpcionesMenu_Horarios_HorarioId" FOREIGN KEY ("HorarioId") REFERENCES "Horarios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OpcionesMenu_Menus_MenuId" FOREIGN KEY ("MenuId") REFERENCES "Menus" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OpcionesMenu_Opciones_OpcionIdA" FOREIGN KEY ("OpcionIdA") REFERENCES "Opciones" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OpcionesMenu_Opciones_OpcionIdB" FOREIGN KEY ("OpcionIdB") REFERENCES "Opciones" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OpcionesMenu_Opciones_OpcionIdC" FOREIGN KEY ("OpcionIdC") REFERENCES "Opciones" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OpcionesMenu_Opciones_OpcionIdD" FOREIGN KEY ("OpcionIdD") REFERENCES "Opciones" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OpcionesMenu_Opciones_OpcionIdE" FOREIGN KEY ("OpcionIdE") REFERENCES "Opciones" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "RolesUsuario" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RolId" integer NOT NULL,
    "UsuarioId" integer NOT NULL,
    CONSTRAINT "PK_RolesUsuario" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RolesUsuario_Roles_RolId" FOREIGN KEY ("RolId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RolesUsuario_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RespuestasFormulario" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpleadoId" integer NOT NULL,
    "OpcionMenuId" integer NOT NULL,
    "SucursalEntregaId" integer NOT NULL,
    "LocalizacionEntregaId" integer,
    "AdicionalOpcionId" integer,
    "Seleccion" character(1) NOT NULL,
    CONSTRAINT "PK_RespuestasFormulario" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RespuestasFormulario_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RespuestasFormulario_Localizaciones_LocalizacionEntregaId" FOREIGN KEY ("LocalizacionEntregaId") REFERENCES "Localizaciones" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RespuestasFormulario_OpcionesMenu_OpcionMenuId" FOREIGN KEY ("OpcionMenuId") REFERENCES "OpcionesMenu" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RespuestasFormulario_Opciones_AdicionalOpcionId" FOREIGN KEY ("AdicionalOpcionId") REFERENCES "Opciones" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RespuestasFormulario_Sucursales_SucursalEntregaId" FOREIGN KEY ("SucursalEntregaId") REFERENCES "Sucursales" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE INDEX "IX_AspNetUsers_EmpleadoId" ON "AspNetUsers" ("EmpleadoId");

CREATE INDEX "IX_AspNetUsers_EmpresaId" ON "AspNetUsers" ("EmpresaId");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Empleados_SucursalId" ON "Empleados" ("SucursalId");

CREATE UNIQUE INDEX "IX_EmpleadosLocalizaciones_EmpleadoId_LocalizacionId" ON "EmpleadosLocalizaciones" ("EmpleadoId", "LocalizacionId");

CREATE INDEX "IX_EmpleadosLocalizaciones_LocalizacionId" ON "EmpleadosLocalizaciones" ("LocalizacionId");

CREATE UNIQUE INDEX "IX_EmpleadosSucursales_EmpleadoId_SucursalId" ON "EmpleadosSucursales" ("EmpleadoId", "SucursalId");

CREATE INDEX "IX_EmpleadosSucursales_SucursalId" ON "EmpleadosSucursales" ("SucursalId");

CREATE INDEX "IX_Localizaciones_EmpresaId" ON "Localizaciones" ("EmpresaId");

CREATE UNIQUE INDEX "IX_Localizaciones_SucursalId_Nombre" ON "Localizaciones" ("SucursalId", "Nombre");

CREATE INDEX "IX_Menus_EmpresaId" ON "Menus" ("EmpresaId");

CREATE INDEX "IX_Menus_SucursalId" ON "Menus" ("SucursalId");

CREATE UNIQUE INDEX "IX_MenusAdicionales_MenuId_OpcionId" ON "MenusAdicionales" ("MenuId", "OpcionId");

CREATE INDEX "IX_MenusAdicionales_OpcionId" ON "MenusAdicionales" ("OpcionId");

CREATE INDEX "IX_OpcionesHorarios_HorarioId" ON "OpcionesHorarios" ("HorarioId");

CREATE UNIQUE INDEX "IX_OpcionesHorarios_OpcionId_HorarioId" ON "OpcionesHorarios" ("OpcionId", "HorarioId");

CREATE INDEX "IX_OpcionesMenu_HorarioId" ON "OpcionesMenu" ("HorarioId");

CREATE INDEX "IX_OpcionesMenu_MenuId" ON "OpcionesMenu" ("MenuId");

CREATE INDEX "IX_OpcionesMenu_OpcionIdA" ON "OpcionesMenu" ("OpcionIdA");

CREATE INDEX "IX_OpcionesMenu_OpcionIdB" ON "OpcionesMenu" ("OpcionIdB");

CREATE INDEX "IX_OpcionesMenu_OpcionIdC" ON "OpcionesMenu" ("OpcionIdC");

CREATE INDEX "IX_OpcionesMenu_OpcionIdD" ON "OpcionesMenu" ("OpcionIdD");

CREATE INDEX "IX_OpcionesMenu_OpcionIdE" ON "OpcionesMenu" ("OpcionIdE");

CREATE INDEX "IX_RespuestasFormulario_AdicionalOpcionId" ON "RespuestasFormulario" ("AdicionalOpcionId");

CREATE INDEX "IX_RespuestasFormulario_EmpleadoId" ON "RespuestasFormulario" ("EmpleadoId");

CREATE INDEX "IX_RespuestasFormulario_LocalizacionEntregaId" ON "RespuestasFormulario" ("LocalizacionEntregaId");

CREATE INDEX "IX_RespuestasFormulario_OpcionMenuId" ON "RespuestasFormulario" ("OpcionMenuId");

CREATE INDEX "IX_RespuestasFormulario_SucursalEntregaId" ON "RespuestasFormulario" ("SucursalEntregaId");

CREATE INDEX "IX_RolesUsuario_RolId" ON "RolesUsuario" ("RolId");

CREATE INDEX "IX_RolesUsuario_UsuarioId" ON "RolesUsuario" ("UsuarioId");

CREATE INDEX "IX_Sucursales_EmpresaId" ON "Sucursales" ("EmpresaId");

CREATE INDEX "IX_SucursalesHorarios_HorarioId" ON "SucursalesHorarios" ("HorarioId");

CREATE UNIQUE INDEX "IX_SucursalesHorarios_SucursalId_HorarioId" ON "SucursalesHorarios" ("SucursalId", "HorarioId");

CREATE UNIQUE INDEX "IX_Usuarios_EmpleadoId" ON "Usuarios" ("EmpleadoId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260102164348_InitialPostgres', '8.0.7');

COMMIT;

START TRANSACTION;

ALTER TABLE "Sucursales" ADD "Rnc" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260102202843_AddSucursalRnc', '8.0.7');

COMMIT;

START TRANSACTION;

ALTER TABLE "Localizaciones" ADD "Rnc" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260103141229_AddLocalizacionRnc', '8.0.7');

COMMIT;

